In [2]:
import numpy as np
from pandas import Series, DataFrame
df = DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])


In [3]:
df.head(1)

A         B         C         D
0  0.121143 -0.529723 -0.051994  0.715554

In [4]:
print(np.random.randn(10, 4))

[[-0.92957547  1.01925524 -0.10178968  0.3305227 ]
 [ 0.37297625  1.87972573  0.40351933 -0.64595842]
 [ 0.23288401  0.00443078 -0.39775198 -0.19351619]
 [-0.3717675   1.61091088 -1.64509501  0.68767093]
 [ 0.70554166  0.27164054 -0.79373345  0.36390919]
 [-0.55130683  1.41175134  0.7108658  -0.22576155]
 [-0.08051397 -0.32228207 -2.32188194  0.30823435]
 [-0.94238799  0.81085069 -0.19719562 -0.51701041]
 [-2.08403132 -1.17852996 -0.47832125 -0.13817129]
 [-1.2129681  -0.42375061  0.53574383 -0.66165775]]


In [5]:
np.random.randn(10)

array([-1.03198016,  1.4982833 , -1.20506814, -0.15368966,  0.52523206,
       -0.06694598, -0.762024  ,  0.44197168, -1.21908834, -0.03072939])

In [7]:
import pandas as pd
import numpy as np
dataCount = 10
data = {'國家':  [ "country"+str(i) for i in range(dataCount)],
        '人口':  np.random.randint(100000,size=dataCount)}
df = pd.DataFrame(data)
df.head()

國家     人口
0  country0   9050
1  country1  19132
2  country2  85396
3  country3  61741
4  country4  33041

In [38]:
#one hot encoding
df = pd.DataFrame(
    data=[["a","b"],
          ["c","d"]],
    columns =["TEXT_VALUE","text2"])
print(df)
one_hot_encoding = pd.get_dummies(df['TEXT_VALUE'])

print(one_hot_encoding)

sub_train = pd.DataFrame(df['TEXT_VALUE'])

print(sub_train)
pd.get_dummies(sub_train)

  TEXT_VALUE text2
0          a     b
1          c     d
   a  c
0  1  0
1  0  1
  TEXT_VALUE
0          a
1          c


TEXT_VALUE_a  TEXT_VALUE_c
0             1             0
1             0             1

In [41]:
df = pd.DataFrame(
    data=[["c","b"],
          ["a","d"]],
    columns =["TEXT_VALUE","text2"])

from sklearn.preprocessing import LabelEncoder
# Create a label encoder object
le = LabelEncoder()
le_count = 0

# Iterate through the columns
for col in df:
    if df[col].dtype == 'object':
        # Train on the training data
        le.fit(df[col])
        # Transform both training and testing data
        df[col] = le.transform(df[col])
        
        # Keep track of how many columns were label encoded
        le_count += 1
        print(df[col])
        
print('%d columns were label encoded.' % le_count)
df

0    1
1    0
Name: TEXT_VALUE, dtype: int64
0    0
1    1
Name: text2, dtype: int64
2 columns were label encoded.


TEXT_VALUE  text2
0           1      0
1           0      1

In [43]:
dat1 = pd.DataFrame({'dat1': [9,5]})
dat2 = pd.DataFrame({'dat2': [7,6]})
dat3 = dat1.join(dat2)
print(dat3)

   dat1  dat2
0     9     7
1     5     6


# EDA


https://matplotlib.org/gallery/index.html
https://seaborn.pydata.org/examples/index.html
http://www.hmwu.idv.tw/web/R_AI_M/AI-M1-hmwu_R_Stat&Prob_v2.pdf
https://www.healthknowledge.org.uk/public-health-textbook/research-methods/1b-statistical-methods/statistical-distributions


In [49]:
df = pd.DataFrame(
    data=[[1,2],
          [3,4],
          [5,6],
          [7,8],
          [100,200],
         ],
    columns =["col1","col2"])
df["col1"].describe()

count      5.000000
mean      23.200000
std       42.990697
min        1.000000
25%        3.000000
50%        5.000000
75%        7.000000
max      100.000000
Name: col1, dtype: float64